/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProgramsIndexImport } from './routes/programs/index'
import { Route as ProgramsProgramidImport } from './routes/programs/$program_id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProgramsIndexRoute = ProgramsIndexImport.update({
  path: '/programs/',
  getParentRoute: () => rootRoute,
} as any)

const ProgramsProgramidRoute = ProgramsProgramidImport.update({
  path: '/programs/$program_id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/programs/$program_id': {
      id: '/programs/$program_id'
      path: '/programs/$program_id'
      fullPath: '/programs/$program_id'
      preLoaderRoute: typeof ProgramsProgramidImport
      parentRoute: typeof rootRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programs/$program_id': typeof ProgramsProgramidRoute
  '/programs': typeof ProgramsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programs/$program_id': typeof ProgramsProgramidRoute
  '/programs': typeof ProgramsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/programs/$program_id': typeof ProgramsProgramidRoute
  '/programs/': typeof ProgramsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programs/$program_id' | '/programs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programs/$program_id' | '/programs'
  id: '__root__' | '/' | '/programs/$program_id' | '/programs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramsProgramidRoute: typeof ProgramsProgramidRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramsProgramidRoute: ProgramsProgramidRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/programs/$program_id",
        "/programs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/programs/$program_id": {
      "filePath": "programs/$program_id.tsx"
    },
    "/programs/": {
      "filePath": "programs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
